[package]
name = "pcemu-rs"
version = "0.1.0"
license = "BSD-2-Clause"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x86_rs = { path = "x86_rs" }